---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hyperspike.io
  resources:
  - auths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hyperspike.io
  resources:
  - auths/finalizers
  verbs:
  - update
- apiGroups:
  - hyperspike.io
  resources:
  - auths/status
  verbs:
  - get
  - patch
  - update
